### ISSUE TITLE
SOCKS request rejected or failed - Signature error

### ISSUE THREAD

**Issue by maikohoney** [javerous/TorChat-Mac#11]
I'm using Mac 10.10.5
Torchat 1.2.3 (a704f70)

This began happening recently, and seemed to be a problem after a new friend tried to add me, although that's probably not related. The error messages are as follows:

From Globals:
[SMTorManagerErrorRetrieveRemoteInfo] Can't retrieve remote informations. {SMTorManagerErrorOperationSignature - Signature error]

and from all my buddy logs:
[TCBuddyEventConnectedTor] Buddy connected on tor SOCKS
[TCBuddy ErrorSocks] SOCKS request rejected or failed.

Please help? Thanks

**Comment by javerous** [comment]
About signature error : it's because I regenerated more secure keys which are not compatible with old version. You should use at least version 1.2.4. Note : this error is only related to tor binary update checking (TorChat can work fine without being able to check if new version of tor is available).

About SOCKS errors, it's common to see that if the tor binary just launched. But if it continues forever (like more than 5 minutes), perhaps there is a problem with either tor, either network.

Can you try with TorChat 1.2.5 (the last version compatible with macOS 10.10 - TorChat 1.3.0 requires macOS 10.11 at least)

**Comment by maikohoney** [comment]
1.2.4 and 1.2.5 do not work.
I've downloaded both, 
1.2.5 is incompatible with 10.10.5
1.2.4 doesn't allow me to enter a password to launch. Keyboard will not enter anything into password field.

**Comment by maikohoney** [comment]
so now I've just moved all my old config files to a back up folder, and tried 1.2.4
It will not allow me to select an existing config file

**Comment by maikohoney** [comment]
1.2.4 will not install new configuration, or allow me to select old config file. It's not working.

**Comment by maikohoney** [comment]
so the old version doesn't work because you changed signatures... Do you have any other solutions I can use on my Mac without ALSO upgrading my OS? Does anyone have any other solutions that would enable me to keep using torchat?

**Comment by javerous** [comment]
Hmm okay. I don't have any macOS 10.10 to test. Perhaps you should consider updating your macOS (it's always a good thing to do : Apple doesn't support more than 2 versions of macOS, and security updates are often done in priority for current version).

I don't have a solution to your problem for now. Do you confirm that the "SOCKS request rejected or failed." is printed forever ?

**Comment by maikohoney** [comment]
Yes, I confirm... it simply keeps repeating in log file every few seconds

**Comment by maikohoney** [comment]
I updated my OS to 10.12 Sierra
I installed Torchat for Mac 1.3 and used the old configuration file
I'm still seeing the error for all my buddies
"SOCKS request rejected or failed"

**Comment by javerous** [comment]
Can you give me a torchat address so I can add you and test further ?

**Comment by maikohoney** [comment]
xlkt34ztvecq7yj3

**Comment by maikohoney** [comment]
Thanks for you help

**Comment by javerous** [comment]
Note : a chat was possible between us. The error is probably due to offline contacts (tor generic connectivity error).
