### ISSUE TITLE
Problems Connecting to other users

### ISSUE THREAD

**Issue by CaptainNyan** [javerous/TorChat-Mac#3]
When I try to connect to users I know are online, it shows them as offline and i cannot message them. Is this a known problem?

**Comment by unchartedmeridians** [comment]
Was this ever resolved? I'm having the exact same problem.

**Comment by javerous** [comment]
@unchartedmeridians If you have the same logs as @TorsHammer, then I can't do anything. Tor itself is unable to connect us to the remote buddy for whatever reason, and I don't have control on this.

**Comment by javerous** [comment]
I enhanced a little bit error handling in current source code. If some of you want to test if it helps for this problem, let me know : I can make a test build (or you can compile the project by yourself).
