### ISSUE TITLE
Can't get current commit hash

### ISSUE THREAD

**Issue by Sarcotome** [javerous/TorChat-Mac#4]
Anyone knows how to fix that when compiling?

**Comment by d3QUone** [comment]
do `git clone` instead of downloading zip to store commit history

**Comment by javerous** [comment]
Yes that's something that I need to fix when we build the app from a directory which is not git-backended.

**Comment by d3QUone** [comment]
BTW I have some problems with TorChat IM adress - waiting is already too long

**Comment by javerous** [comment]
Yes some people have this problem, but I can't see a problem in my code about that point. And the logs reported tends to indicate that it's due to tor itself, which seem to have difficulties to reach some hidden addresses for whatever reason.

**Comment by d3QUone** [comment]
So what the best I can do to connect to chat?

**Comment by javerous** [comment]
No idea :( The only way I see is to don't use the integrated Tor, which is launched each time TorChat is launched (and killed each time TorChat is terminated), but use an external Tor instance.

Tor use a lot of time to bootstrap (or discover network) on each launch. If you use an external Tor binary, you have the chance to let it alive longer (and so be quicker to reach hidden addresses).

On my side, just after a launch, with the integrated Tor binary, users appear usually online after max 5 minutes.

**Comment by d3QUone** [comment]
Can you share your integrated binary? Is it safe? Or can you help to integrate it?

**Comment by d3QUone** [comment]
It seems like chat is running ok when launched from Xcode (not from archived application). Can you send your address to check if it works correctly?

**Comment by d3QUone** [comment]
Help please
