### ISSUE TITLE
Which branch to pick?

### ISSUE THREAD

**Issue by onionuser** [javerous/TorChat-Mac#5]
In order to build/run tor safely, should I use the branch 'master' or 'tor-update'? The master looks outdated, but at the same time it's the latest official release, right? 

The Tor version for windows comes in two version, there is an outdated one and a newer update. They said that it is highly recommended to update. Needs the OSX version this as well?

**Comment by javerous** [comment]
You should use 'master'. The branch 'tor-update' is work in progress (I'm late on it because I don't have much free time).

**Comment by onionuser** [comment]
Thank you for responding quickly.
I still like to know if the 'master' is relatively safe to use. Are there any security issues to consider? Contains 'tor-update' only minor bug fixes or also important security improvements? Can you say something about that? Thanks!

**Comment by javerous** [comment]
The branch 'tor-update" don't fix any security problem. It's just a new feature to be able to update automatically the wrapped tor binary.

The only problem I can see in 'master' branch is that the wrapped tor binary is a little bit old. To be perfect, you can just replace it with the last one included in Tor Browser.

**Comment by Gyvastis** [comment]
And could you tell me how to build it exactly?

**Comment by javerous** [comment]
@Gyvastis Just open the Xcode project and build it.
